Repository gip-inclusion/pilotage-airflow, pull requests merged in 2025-09, with the labels that each got.

#520 Mise à jour des dépendances
  custom-prod-entrypoint.sh
  dbt/models/ephemeral/eph_series_mois.sql
  dbt/models/indexed/sorties_v2.sql
  dbt/models/legacy/daily/candidatures_recues_par_fiche_de_poste.sql
  dbt/models/legacy/weekly/fluxIAE_AnnexeFinanciere_v2.sql
  dbt/models/marts/daily/candidats.sql
  dbt/models/marts/daily/candidats_odc.sql
  dbt/models/marts/daily/candidatures_candidats_recherche_active.sql
  dbt/models/marts/daily/candidatures_echelle_locale.sql
  dbt/models/marts/daily/candidatures_odc.sql
  dbt/models/marts/daily/candidatures_par_candidat.sql
  dbt/models/marts/daily/suivi_candidatures_prescripteurs_habilites.sql
  dbt/models/marts/daily/taux_refus_structures.sql
  dbt/models/marts/daily/utilisateurs.sql
  dbt/models/marts/daily/utilisateurs_jamais_venus.sql
  dbt/models/marts/weekly/etp_par_salarie.sql
  dbt/models/marts/weekly/marche_suivi_structure.sql
  dbt/models/marts/weekly/suivi_consommation_mensuelle_etp_V2.sql
  dbt/models/marts/weekly/suivi_etp_realises_v2.sql
  dbt/models/marts/weekly/suivi_realisation_convention_mensuelle.sql
  dbt/models/marts/weekly/suivi_realisation_convention_par_structure.sql
  dbt/models/staging/stg_bassin_emploi.sql
  dbt/models/staging/stg_candidats.sql
  dbt/models/staging/stg_candidats_asp_derniere_sortie.sql
  dbt/models/staging/stg_consommation_etp.sql
  dbt/models/staging/stg_etat_mensuel_individuel_avec_brsa.sql
  dbt/models/staging/stg_etp_conventionnes.sql
  dbt/models/staging/stg_fdp_candidatures.sql
  dbt/models/staging/stg_reseaux.sql
  requirements/base.txt
  requirements/dev.txt
Labels: changelog:non, datasource:non

#526 Airflow : Désactivation du méchanisme de rattrapage
  .env-base
Labels: changelog:non, datasource:non

#528 DAG : Ajout de l'option `7zip` pour `stats_dsn`
  dags/stats_dsn.py
Labels: changelog:ajouté, datasource:dsn

#529 [monrecap] Fix rapide du barometre
  dags/monrecap.py
Labels: changelog:non, datasource:monrecap

#535 [Tracking] Suivi des deux nouvelles version des TBs ETPs
  dbt/seeds/pilotage_interne/metabase_dashboards.csv
Labels: changelog:non, datasource:non
