Repository gip-inclusion/pilotage-airflow, pull requests merged in 2025-06, with the labels that each got.

#462 Résolution des valeurs nulls de contrat_id dans stg_contrats
  dbt/models/indexed/properties.yml
  dbt/models/staging/stg_contrats.sql
Labels: changelog:modifié, datasource:asp

#463 Ajout d'une seed contenant la correspondance commune - clpe
  dbt/seeds/properties.yml
  dbt/seeds/ref_clpe_ft.csv
Labels: changelog:ajouté, datasource:france-travail

#457 [Mon recap] Correction du doublon de colonnes et du changement des modeles airtable
  dags/monrecap.py
  dbt/models/monrecap/staging/stg_contacts_commandeurs.sql
  dbt/models/monrecap/staging/stg_contacts_non_commandeurs.sql
Labels: changelog:non, datasource:non

#466 [Beneficiaires] Caractéristiques des bénéficiaires par salarié
  dbt/models/marts/weekly/caracteristiques_beneficiaires.sql
  dbt/models/marts/weekly/properties.yml
Labels: changelog:ajouté, datasource:asp

#468 changement stg_contrat nombre heures travaillées
  dbt/models/marts/weekly/contrats.sql
  dbt/models/marts/weekly/formations.sql
  dbt/models/marts/weekly/properties.yml
  dbt/models/staging/stg_contrats.sql
  dbt/models/staging/stg_contrats_parent.sql
Labels: changelog:modifié, datasource:asp

#469 Table caracteristiques_beneficiaires : Ajout de la date de sortie
  dbt/models/marts/weekly/caracteristiques_beneficiaires.sql
Labels: changelog:non, datasource:asp

#472 [monrecap] ajout des regions dans les tables monrecap
  dbt/models/monrecap/marts/Commandes.sql
  dbt/models/monrecap/marts/barometre.sql
  dbt/models/monrecap/staging/stg_contacts_commandeurs.sql
  dbt/models/monrecap/staging/stg_contacts_non_commandeurs.sql
  dbt/models/monrecap/staging/stg_departement_derniere_commandes.sql
  dbt/seeds/dep_reg_ref_emplois.csv
Labels: changelog:non, datasource:monrecap

#474 [monrecap] Fix doublons region dans la table barometre
  dbt/models/monrecap/staging/stg_departement_derniere_commandes.sql
Labels: changelog:non, datasource:monrecap

#470 Ajouter les caractéristiques bénéficiaires à la table "parcours_salarie"
  dbt/models/ephemeral/eph_caracteristiques_beneficiaires_per_hash_nir.sql
  dbt/models/ephemeral/properties.yml
  dbt/models/marts/weekly/caracteristiques_beneficiaires.sql
  dbt/models/marts/weekly/parcours_salarie.sql
  dbt/models/staging/properties.yml
  dbt/models/staging/stg_caracteristiques_beneficiaires_ordonnees_per_hash_nir.sql
  dbt/models/staging/stg_contrats_parent.sql
  dbt/models/staging/stg_parcours_salarie_info_contrats.sql
Labels: changelog:modifié, datasource:asp

#477 DAG : Suppression des tâches `dbt clean`
  dags/dbt_daily.py
  dags/dbt_france_travail.py
  dags/dbt_oneshot.py
  dags/dbt_snapshot.py
  dags/dbt_weekly.py
Labels: changelog:non, datasource:non

#456 Creation dag pour obtenir donnée immersion facilitée
  dags/common/anonymize_sensible_data.py
  dags/common/flux_iae.py
  dags/common/france_travail/models.py
  dags/common/immersion_facilitee/__init__.py
  dags/common/immersion_facilitee/helpers.py
  dags/common/immersion_facilitee/models.py
  dags/immersions_facilitee.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.in
  requirements/dev.txt
  tests/conftest.py
  tests/test_common_anonymize_sensible_data.py
Labels: changelog:ajouté, datasource:if

#485 Flux IAE : Correction des hash pour les PASS et agréments vides
  dags/common/flux_iae.py
Labels: changelog:non, datasource:asp
