Repository gip-inclusion/pilotage-airflow, pull requests merged in 2025-07, with the labels that each got.

#487 Mise à jour de Airflow en 2.11.0
  .env-base
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
Labels: changelog:tech, datasource:non

#490 Ajout suspensions_v0 au make_dump
  Makefile
Labels: changelog:ajouté, datasource:non

#495 [Mon Récap] Prendre en compte un ajout de colonnes dans le barometre
  dags/monrecap.py
Labels: changelog:non, datasource:monrecap

#489 DAG : Utiliser `--static` pour n'avoir qu'un fichier a téléverser pour `generate_docs`
  dags/common/operators.py
  dags/generate_docs.py
Labels: changelog:non, datasource:non

#498 Modification de la jointure pour obtenir la table les_emplois_contrats
  dbt/models/marts/weekly/les_emplois_contrats.sql
  dbt/models/marts/weekly/properties.yml
  dbt/tests/test_emplois_contrats.sql
Labels: changelog:ajouté, datasource:asp

#500 Correction des valeurs NaN et 999
  dags/common/esat/ESAT_variables_questionnaire2025.csv
  dags/common/esat/helpers.py
Labels: changelog:non, datasource:non

#501 adapt code to prod data schema
  dags/common/immersion_facilitee/helpers.py
  dags/common/immersion_facilitee/models.py
Labels: changelog:modifié, datasource:if

#502 add prescriptor to dihal candidatures
  dbt/models/marts/daily/candidatures_dihal.sql
Labels: changelog:ajouté, datasource:les-emplois

#505 Ajout département_orga à table stg_candidats_candidatures
  dbt/models/staging/stg_candidats_candidatures.sql
Labels: changelog:ajouté, datasource:les-emplois

#506 Ajoute numéro département aux tables taux_trasformation et stg_organisations
  dbt/models/marts/daily/taux_transformation_prescripteurs.sql
  dbt/models/staging/stg_organisations.sql
Labels: changelog:ajouté, datasource:les-emplois

#508 Ajout du numéro de departement à la table benef & sorties
  dbt/models/marts/oneshot/fluxIAE_BenefSorties_ASP_v2.sql
  dbt/seeds/department_asp.csv
Labels: changelog:non, datasource:asp

#512 Ajout du suivi de deux TBs privés
  dbt/seeds/pilotage_interne/metabase_dashboards.csv
Labels: changelog:non, datasource:non
