Repository gip-inclusion/pilotage-airflow, pull requests merged in 2025-05, with the labels that each got.

#452 github : Ne plus forcer la présence de label pour les PR `dependencies`
  .github/workflows/require-labels.yml
Labels: dependencies

#446 Création d'une table bénéficiaires regroupant le fluxIAE et l'extraction ponctuelle (cab) de l'ASP
  dbt/.gitignore
  dbt/models/_sources.yml
  dbt/models/ephemeral/eph_dates_etat_mensuel_individualise.sql
  dbt/models/indexed/fluxIAE_ContratMission_v2.sql
  dbt/models/indexed/fluxIAE_Salarie_v2.sql
  dbt/models/marts/weekly/beneficiaires.sql
  dbt/models/marts/weekly/beneficiaires_sorties.sql
  dbt/models/marts/weekly/int_beneficiaires_sorties.sql
  dbt/models/marts/weekly/properties.yml
  dbt/models/marts/weekly/suivi_etp_realises_v2.sql
  dbt/models/staging/stg_etat_mensuel_individuel_avec_brsa.sql
  dbt/tests/test_suivi_etp_realises_v2_sum_etp.sql
Labels: changelog:ajouté, datasource:asp

#440 Ajout du nombre de candidatures provenant d'une autoprescription
  dbt/models/ephemeral/eph_nbr_candidatures.sql
  dbt/models/marts/daily/nombre_candidatures_par_structure.sql
  dbt/models/staging/properties.yml
  dbt/models/staging/stg_candidatures_autoprescription.sql
Labels: changelog:modifié, datasource:les-emplois

#460 [ASP] Seed pour matcher les données dpt/reg asp et pilotage
  dbt/models/marts/oneshot/fluxIAE_BenefSorties_ASP_v2.sql
  dbt/seeds/department_asp.csv
  dbt/seeds/properties.yml
  dbt/seeds/region_asp.csv
Labels: changelog:non, datasource:asp
